-- MySQL Script generated by MySQL Workbench
-- Mon Jan 29 16:36:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parameter_list
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `parameter_list` ;

-- -----------------------------------------------------
-- Schema parameter_list
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parameter_list` DEFAULT CHARACTER SET utf8 ;
USE `parameter_list` ;

-- -----------------------------------------------------
-- Table `parameter_list`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`attribute` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`attribute` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1788
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`reference` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`reference` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL DEFAULT NULL,
  `Author` VARCHAR(45) NULL DEFAULT NULL,
  `Publication` VARCHAR(45) NULL DEFAULT NULL,
  `URL` VARCHAR(45) NULL DEFAULT NULL,
  `Keywords` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2633
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`unit` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`unit` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3129
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`parameter` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`parameter` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Unit_id` INT(11) NULL DEFAULT NULL,
  `Definition` VARCHAR(100) NULL DEFAULT NULL,
  `Date_modified` DATE NULL DEFAULT NULL,
  `Reference_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_unit_id` (`Unit_id` ASC),
  INDEX `fk_reference_id_idx` (`Reference_id` ASC),
  CONSTRAINT `fk_reference_id`
    FOREIGN KEY (`Reference_id`)
    REFERENCES `parameter_list`.`reference` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unit_id`
    FOREIGN KEY (`Unit_id`)
    REFERENCES `parameter_list`.`unit` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8055
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`system` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`system` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Parent_id` INT(11) NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8582
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`manager` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`manager` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4726
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`team` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`team` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Parent_id` INT(11) NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Manager_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_manager_id_idx` (`Manager_id` ASC),
  CONSTRAINT `fk_manager_id`
    FOREIGN KEY (`Manager_id`)
    REFERENCES `parameter_list`.`manager` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9513
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`subsystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`subsystem` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`subsystem` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Parent_id` INT(11) NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8582
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`devicetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`devicetype` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`devicetype` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8582
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`version` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`version` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Number` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8582
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`data` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`data` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Team_id` INT(11) NULL DEFAULT NULL,
  `System_id` INT(11) NULL DEFAULT NULL,
  `Subsystem_id` INT(11) NULL,
  `devicetype_id` INT(11) NULL,
  `Value` VARCHAR(200) NULL DEFAULT NULL,
  `Date_modified` DATE NULL DEFAULT NULL,
  `Attribute_id` INT(11) NULL DEFAULT NULL,
  `Parameter_id` INT(11) NULL DEFAULT NULL,
  `Comment` VARCHAR(80) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `Version_id` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_system_id_idx` (`System_id` ASC),
  INDEX `fk_team_id_idx` (`Team_id` ASC),
  INDEX `fk_parameter_id_idx` (`Parameter_id` ASC),
  INDEX `fk_attribute_id_idx` (`Attribute_id` ASC),
  INDEX `fk_subsystem_id_idx` (`Subsystem_id` ASC),
  INDEX `fk_devicetype_id_idx` (`devicetype_id` ASC),
  INDEX `fk_version_id_idx` (`Version_id` ASC),
  CONSTRAINT `fk_attribute_id`
    FOREIGN KEY (`Attribute_id`)
    REFERENCES `parameter_list`.`attribute` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parameter_id`
    FOREIGN KEY (`Parameter_id`)
    REFERENCES `parameter_list`.`parameter` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_id`
    FOREIGN KEY (`System_id`)
    REFERENCES `parameter_list`.`system` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_id`
    FOREIGN KEY (`Team_id`)
    REFERENCES `parameter_list`.`team` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subsystem_id`
    FOREIGN KEY (`Subsystem_id`)
    REFERENCES `parameter_list`.`subsystem` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devicetype_id`
    FOREIGN KEY (`devicetype_id`)
    REFERENCES `parameter_list`.`devicetype` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_version_id`
    FOREIGN KEY (`Version_id`)
    REFERENCES `parameter_list`.`version` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11929
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`re_system_subsystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`re_system_subsystem` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`re_system_subsystem` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `System_id` INT(11) NULL,
  `Subsystem_id` INT(11) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_system_id_idx` (`System_id` ASC),
  INDEX `fk_subsystem_id_idx` (`Subsystem_id` ASC),
  CONSTRAINT `fk_s_system_id`
    FOREIGN KEY (`System_id`)
    REFERENCES `parameter_list`.`system` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_subsystem_id`
    FOREIGN KEY (`Subsystem_id`)
    REFERENCES `parameter_list`.`subsystem` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8582
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parameter_list`.`history_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parameter_list`.`history_data` ;

CREATE TABLE IF NOT EXISTS `parameter_list`.`history_data` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Value` VARCHAR(45) NULL DEFAULT NULL,
  `data_id` INT(11) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_data_id_idx` (`data_id` ASC),
  CONSTRAINT `fk_data_id`
    FOREIGN KEY (`data_id`)
    REFERENCES `parameter_list`.`data` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1788
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
